name: Distribution App

on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  KEYSTORE_FILE: ${{secrets.KEYSTORE_FILE}}
  KEYSTORE_KEY_ALIAS: ${{secrets.KEYSTORE_KEY_ALIAS}}
  KEYSTORE_KEY_PASSWORD: ${{secrets.KEYSTORE_KEY_PASSWORD}}
  KEYSTORE_STORE_PASSWORD: ${{secrets.KEYSTORE_STORE_PASSWORD}}  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}
      
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Decode Keystore File
        id: decode_keystore_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore_release.jks'
          encodedString: ${{secrets.KEYSTORE_FILE}}
          
      - name: Set Decoded File Location as Environment
        run: echo "KEYSTORE_FILE=${{steps.decode_keystore_file.outputs.filePath}}" >> $GITHUB_ENV
        
      - name: Expose Version Name
        uses: michpohl/android-expose-version-name-action@v1.0.0
        with:
          path: app/build.gradle
          expose-version-name: 'true'
          expose-version-code: 'true'
          
    #  - name: Build Debug Artifacts
    #    run: ./gradlew app:assembleDebug
          
    #  - name: Build Release Artifacts
    #    run: ./gradlew app:assembleRelease
        
#     - name: Build Bundle Artifacts
#       run: ./gradlew app:bundleRelease

#     - name: Upload Artifacts to Outputs
#       uses: actions/upload-artifact@v2
#       with:
#         path: |
#           app/build/outputs/apk
#           app/build/outputs/bundle
            
      # Download a build artifact that was previously uploaded in the workflow by the upload-artifact action
#     - name: Download a Build Artifact
#       uses: actions/download-artifact@v2
      
#     - name: Create GitHub Release
#       uses: softprops/action-gh-release@v1
#       with:
#         name: ${{ env.ANDROID_VERSION_NAME }}
#         tag_name: ${{ env.ANDROID_VERSION_NAME }}
#         draft: false
#         prerelease: false
#         files: |
#           app/build/outputs/apk/**/*.apk
#           app/build/outputs/bundle/**/*.aab
          
#     - name: Distribute Artifacts via Firebase
#       run: bash ./gradlew appDistributionUploadRelease --stacktrace
#       env:
#         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

#      - name: Get Commits since last Release
#        id: changes
#        uses: simbo/changes-since-last-release-action@v1
#        with:
#          line-prefix: "â€¢ "
#          include-hashes: true

      - name: Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO_ID}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          disable_notification: false
          disable_web_page_preview: true
          document: app/build/outputs/apk/**/*.apk
          format: markdown
          message: |
            New Artifacts Available in [Repository](https://github.com/${{github.repository}})!
            Include Commits:
            ${{ github.event.head_commit.message }}
            Version: ${{env.ANDROID_VERSION_NAME}}(${{env.ANDROID_VERSION_CODE}})
            Changes since ${{steps.changes.outputs.last-tag}}:
            ${{steps.changes.outputs.log}}
            [See changes](https://github.com/${{github.repository}}/commit/${{github.sha}})
